- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ##APP_NAME##
    name: ##APP_NAME##-deployment
    namespace: default
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: ##APP_NAME##
    strategy:
      spec:
        containers:
        - name: ##APP_NAME##
          image: public.ecr.aws/a9x6t2f1/##APP_NAME##:##VERSION##
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000