- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: webserver
    name: webserver-deployment
    namespace: default
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: webserver
    strategy:
      spec:
        containers:
        - name: webserver
          image: public.ecr.aws/a9x6t2f1/webserver:1.0.0-16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000