apiVersion: v1
kind: Service
metadata:
  name: ##APP_NAME##
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: ##APP_NAME##
  ports:
    - name: ##APP_NAME##
      protocol: TCP
      port: 8000
      targetPort: 8000
