- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: webserver
    name: webserver-service
    namespace: default
  spec:
    type: LoadBalancer
    ports:
    - name: webserver-port
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: webserver
    sessionAffinity: None
