- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ##APP_NAME##
    name: ##APP_NAME##-service
    namespace: default
  spec:
    type: LoadBalancer
    ports:
    - name: ##APP_NAME##-port
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: ##APP_NAME##
    sessionAffinity: None
